"""empty message

Revision ID: 45577501ce87
Revises: 2dd8a1a2521a
Create Date: 2023-07-03 17:17:26.912856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45577501ce87'
down_revision = '2dd8a1a2521a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
