"""empty message

Revision ID: 722340cb0483
Revises: 45577501ce87
Create Date: 2023-07-03 18:48:54.374250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '722340cb0483'
down_revision = '45577501ce87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
