"""empty message

Revision ID: cf973f5f13e8
Revises: 1aec4cb63584
Create Date: 2023-07-03 18:56:20.028188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf973f5f13e8'
down_revision = '1aec4cb63584'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'dislikes')
    op.drop_column('posts', 'likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('likes', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('dislikes', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
