"""empty message

Revision ID: e6d0c2534d2d
Revises: cf973f5f13e8
Create Date: 2023-07-03 19:48:34.753748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6d0c2534d2d'
down_revision = 'cf973f5f13e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('dislikes_post_id_fkey', 'dislikes', type_='foreignkey')
    op.create_foreign_key(None, 'dislikes', 'posts', ['post_id'], ['id'], ondelete='cascade')
    op.drop_constraint('likes_post_id_fkey', 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'posts', ['post_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key('likes_post_id_fkey', 'likes', 'posts', ['post_id'], ['id'])
    op.drop_constraint(None, 'dislikes', type_='foreignkey')
    op.create_foreign_key('dislikes_post_id_fkey', 'dislikes', 'posts', ['post_id'], ['id'])
    # ### end Alembic commands ###
